version: '3'
services:
  backend:
    build: ./Backend
    ports:
      - "3001:3001"
    volumes:
      - ./Backend:/app
    environment:
      - NODE_ENV=production

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/app